### ISSUE TITLE
Load more button not shown

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3#1384] opened 2015-06-29 16:06 UTC
on mercator staging the load more button is not shown anymore

**Comment by xi** [comment] 2016-02-24 17:18
maybe related to #1622

**Comment by xi** [comment] 2016-02-25 14:07
also related to #1010

**Comment by Johnschmidfront** [comment] 2016-02-29 13:22
@2e2a and I verified that, when in a pool query `sort` is set (to something relevant, like `item_creation_date`), the `count` is restricted by the `limit` parameter and fails to return the total count.

**Comment by Johnschmidfront** [comment] 2016-02-29 13:30
duplicate of  #1622

**Closed** 2016-02-29 13:30 UTC
Labels: backend, bug
