### ISSUE TITLE
Safari Browser crashes when entering Advocate-Europe.eu

### ISSUE THREAD

**Issue by rukala** [liqd/adhocracy3#1867] opened 2015-12-04 09:58 UTC
When I go to advocate-europe.eu in my Safari Browser, the page is constantly reloading which causes my browser to crash.

**Comment by nidico** [comment] 2015-12-04 10:15
The frontpage (https://advocate-europe.eu) or the idea space (https://advocate-europe.eu/de/ideen-raum)?

**Comment by rittermo** [comment] 2015-12-04 10:16
Occurs on all pages
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (mercator_advocate_theme-compiled.css.map, line 0)

**Comment by nidico** [comment] 2015-12-04 14:48
Nadine S. writes that @joka is aware of the issue. It might be caused by the upgrade to Plone 5.0.

**Comment by joka** [comment] 2015-12-04 20:34
How can we test with safari?

**Comment by nidico** [comment] 2015-12-04 20:50
I have a very old safari 5.1.7 installation on my windows 7 virtualbox (AFAIK the last version released for windows, can [still be downloaded](http://www.chip.de/downloads/Safari_27264736.html).

The error can be reproduced on this old version as well.

**Comment by joka** [comment] 2015-12-04 20:54
> I have a very old safari 5.1.7 installation on my windows 7 virtualbox (AFAIK the last version released for windows, can still be downloaded.
> 
> The error can be reproduced on this old version as well.

ah good to know.

**Comment by joka** [comment] 2015-12-04 21:02
> I have a very old safari 5.1.7 installation on my windows 7 virtualbox (AFAIK the last version released for windows, can still be downloaded.
> 
> The error can be reproduced on this old version as well.
> ah good to know.

Ich kann Safari leider nicht testen mit meinem Windows XP da die HTPS Verbindung nicht klappt, vielleicht ist unser HTTPS-Verschlüsselung zu "modern"?

**Comment by nidico** [comment] 2015-12-04 21:08
> Ich kann Safari leider nicht testen mit meinem Windows XP da die HTPS Verbindung nicht klappt, vielleicht ist unser HTTPS-Verschlüsselung zu "modern"?

Probably... It does work on my Win 7.

If you have a local installation, you could go without https though.

**Comment by joka** [comment] 2015-12-04 21:32
Ich kann das  nicht testen und habe auch ehrlich gesagt keine Ahnung woran das liegen könnte.

> Occurs on all pages
> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (mercator_advocate_theme-compiled.css.map, line 0)

This file is only for debugging and is normaly not requested. I added it but this does not help.

This is a javacript bug on safari and I`have no expertise in solving such an issue. 
The only thing I can do is reset the productive server/database to the state before the plone and mercator theme updates.

**Comment by nidico** [comment] 2015-12-04 22:23
> This is a javacript bug on safari and I have no expertise in solving such an issue.

Well, I'd say the normal procedure:

- reproduce locally
- strip down features (I'd start with removing our custom theme / js) until you found the cause

Searching for similar issues, I stumbled upon Modernizr/Modernizr#524. I don't have more time / energy to dig further.

**Comment by joka** [comment] 2015-12-04 22:30
ah if found a plone fix for this while trying to reproduce this with a fresh plone installation.

**Comment by nidico** [comment] 2015-12-04 22:31
How did you fix it?

**Closed by joka** 2015-12-04 22:30 UTC
Labels: bug, critical

**Comment by joka** [comment] 2015-12-04 22:35
> How did you fix it?

I added an updated plone javascript compilatation and i guess requires js was updated, I can figure out more on Monday if you are interested.

I testet it with MacOS 10, Safari 6.2, please  also test other versions.

**Comment by joka** [comment] 2015-12-04 22:36
Thank you all for caring about this issues.

**Comment by nidico** [comment] 2015-12-04 22:40
Great!

Fix confirmed on Safari 5.1.7 / Win7.

**Comment by joka** [comment] 2015-12-04 22:41
> I have a very old safari 5.1.7 installation on my windows 7 virtualbox (AFAIK the last version released for windows, can still be downloaded).

In the end I used  the virtual machine of the "crossbrowsertesting" webservice ( 1 hour vm runtime for free)
