### ISSUE TITLE
comments_count broken

### ISSUE THREAD

**Issue by Johnschmidfront** [liqd/adhocracy3#2055] opened 2016-02-11 10:36 UTC
- The comment count displayed under the speechbubble isn't updated directly after creating/ deleting comments - I need to refresh to update it.
- If I delete 1 comment with 1 reply, comment count currently gets -1, but it should get -2.

**Comment by xi** [comment] 2016-02-15 09:30
> The comment count displayed under the speechbubble isn't updated directly after creating/ deleting comments - I need to refresh to update it.

Duplicate of #410

> If I delete 1 comment with 1 reply, comment count currently gets -1, but it should get -2.

Duplicate of #549

**Closed by xi** 2016-02-15 09:30 UTC
Labels: backend, bug
