### ISSUE TITLE
A3 backend deletes last letter from user paths during permission checks

### ISSUE THREAD

**Issue by ChristianSi** [liqd/adhocracy3#1508] opened 2015-08-03 15:47 UTC
To identify the logged-in user, the frontend (or the Thentos proxy) send a header such as

    X-User-Path: http://127.0.0.1:6546/principals/users/0000001/
    X-User-Path: http://127.0.0.1:6546/principals/users/0000001

Supposedly both variants (with or without trailing slash) should be equivalent, and indeed are both correctly identified as the same user, but in the authorization step something breaks when the trailing slash is omitted.

In `adhocracy_core/authorization/__init__.py`, the RoleACLAuthorizationPolicy.permits method receives the following list of principals in that case:

    ['system.Everyone', 'system.Authenticated', '/principals/users/000000']

So the last digit of the user ID got at some point deleted (0000001 became 000000)!

In result, supposedly because there is no user with ID 000000, the permission check fails with "403 Forbidden Unauthorized: PoolRESTView failed permission check" even for simple GET requests to the `mercator/` root element.

This was very surprising and quite annoying to debug, therefore the behavior should be changed.

Either the slashless variant should be rejected with a clear error message or (preferably) it should be treated as identical to the slashed one.

**Comment by pallix** [comment] 2015-08-03 16:59
I will have a look tomorrow but in the mean time, here some thoughts:

Even if the user path is invalid (=bug) my guess is that the request should success as, if I understand correctly, with  'system.Authenticated' role you should get also 'participant' role. Can it be that the workflow state is set to 'draft' instead of 'participate'?

**Comment by ChristianSi** [comment] 2015-08-04 08:26
@pallix No, if I'm not logged in (i.e, just 'system.Everyone' I presume) I can view the page just fine, but If I'm logged in with such broken user it's forbidden (403). How it can be that additional principals *reduce* the permission set I do now know, but it's clearly the case.

There may be a secondary bug lurking...

**Comment by pallix** [comment] 2015-08-04 09:06
I cannot reproduce it. 

All `X-User-Path` in `testing.py` don't end with a leading slash and settings a breakpoint in the [authorization module](https://github.com/liqd/adhocracy3.mercator/blob/1dad266b928a6555b459e7626dcc4f1947d29571/src/adhocracy_core/adhocracy_core/authorization/__init__.py#L48) while executing `test_digital_leben.py` shows that the path is not trimed

**Comment by ChristianSi** [comment] 2015-08-04 10:19
Strange, then it seems to happen only when the backend is actually running on a webserver. I can reproduce it as follows (on current master):

Log in using the frontend and snoop user path and token sent by the frontend.

Send the following request via curl (adapting path, token and backend url as needed):

    curl -v -H "X-User-Path: http://127.0.0.1:6541/principals/users/0000001/" -H "X-User-Token: ..." http://localhost:6541/mercator/

The response should start with "HTTP/1.1 200 OK".

Repeat without the trailing slash:

    curl -v -H "X-User-Path: http://127.0.0.1:6541/principals/users/0000001" -H "X-User-Token: ..." http://localhost:6541/mercator/

Now the response starts with "HTTP/1.1 403 Forbidden".

(Once #1511 is merged it'll also be possible to do this without setting the "X-User-Token" header.)

**Comment by joka** [comment] 2016-04-27 17:18
This is fixed now with #2110 and  #2271

**Closed by joka** 2016-04-27 17:18 UTC
Labels: backend, bug
