### ISSUE TITLE
Owner cannot PUT on his own proposal

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3#1933] opened 2015-12-22 16:15 UTC
in AE, when I create a proposal that is not admin and then make an OPTIONS request on that proposal with the owner being logged in I am only allowed to GET (at least that is, what OPTIONS tells me)

**Comment by pallix** [comment] 2016-01-04 13:20
I cannot reproduce it on staging. Do you still have the problem?

**Comment by pallix** [comment] 2016-01-06 15:36
Closing this as we saw with Magda that the backend result are indeed correct.

**Closed by pallix** 2016-01-06 15:36 UTC
Labels: backend
