### ISSUE TITLE
mein.Berlin Project: BUG on detail page (Bürgerhaushalt)

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/adhocracy3#2021] opened 2016-01-29 12:22 UTC
I found a bug on mein.Berlin. 
if you go to the tile Bürgerhaushalt (the only process that is in participation phase) and click on it you’ll be directed to a detail page on berlin.de.
If you choose 'Vorschlag anlegen' and then go to the map overview on the iFrame there you’ll see that, on the bottom of the iFrame, the map is not displayed completely.

![screen shot 2016-01-29 at 13 20 20](https://cloud.githubusercontent.com/assets/15954895/12675528/3a508f2a-c68b-11e5-8894-3194affdb322.png)

**Comment by Johnschmidfront** [comment] 2016-02-01 09:56
This bug only occurs if you are using a Mac and only if you directly click 'Vorschlag anlegen'/ 'Create proposal' - it doesn't occur if you first click on the 'map' icon and then click on 'Create proposal'. The issue, according to @xi, is that the scrollbar isn't created, so you can't access the lower part of the iframe.

**Comment by xi** [comment] 2016-02-02 09:32
I was not able to reproduce it, even with help from @gereonrahnfeld. Until we get more information there is nothing we can do.

**Comment by xi** [comment] 2016-04-04 15:33
Closing. We can reopen in case it happens again.

**Closed by xi** 2016-04-04 15:33 UTC
Labels: bug
