### ISSUE TITLE
[s1] Uploaded images are not served from backend

### ISSUE THREAD

**Issue by dwt** [liqd/adhocracy3#2555] opened 2016-07-28 11:13 UTC
Uploading seems to work, but when trying to download the images again, I get this error

```json
{
"errors": [
{
"location": "url",
"name": "GET",
"description": "403 Forbidden Unauthorized: AssetDownloadRESTView failed permission check"
}
],
"status": "error"
}
```

**Comment by dwt** [comment] 2016-07-28 11:14
To reproduce, go to the users page (in s1), click the user image placeholder, select an image to upload, upload.

Now the image should be shown - but it isn't. Instead one gets the 'image missing' placeholder.

Digging deeper, one gets the error printed above.

**Comment by xi** [comment] 2016-08-01 08:27
Could this be a duplicate of #1973?

**Comment by 2e2a** [comment] 2016-08-01 09:38
> Could this be a duplicate of #1973?

Yes, its the same issue.

**Closed** 2016-08-01 09:44 UTC
Labels: duplicate
