### ISSUE TITLE
can't open terms and conditions

### ISSUE THREAD

**Issue by stadine** [liqd/adhocracy3#2135] opened 2016-03-07 12:49 UTC
It's not possible to open the link »terms and condition« 

https://advocate-europe.eu/en/idea-space#!/register
https://www.berlin.de/buergeraktiv/aktuelles/berliner-engagementlandschaft/thesen-zur-berliner-engagementlandschaft/artikel.448132.php

**Comment by xi** [comment] 2016-03-07 12:57
This is probably a deployment issue caused by the changes from #2018. @slomo, @2e2a could you please have a look?

**Comment by 2e2a** [comment] 2016-03-07 13:49
The deployment has been adjusted to use the parameter:
adhocracy.frontend.terms_url.de/en

**Comment by Johnschmidfront** [comment] 2016-03-23 15:39
@2e2a @stadine Can we close the issue?

**Comment by xi** [comment] 2016-04-19 11:53
Still not fixed for advocate europe

**Comment by slomo** [comment] 2016-04-20 07:59
The config values have the right name and they are exposed in the frontends [config.json](https://frontend.advocate-europe.eu/config.json). But still the links doesn't work. I assume it is some bug.   This bug has been fixed on [advocate stage](https://a3-stage.liqd.net/register). So we are just waiting for redeployment. I would vote for closing this issue since it seems not to be A3 at fault. And deployment issues should not be tracked here.

**Comment by xi** [comment] 2016-04-20 08:36
Ok, as you do not forget about this, I agree the issue can be closed.

**Closed by xi** 2016-04-20 08:36 UTC
Labels: bug, high prio
